adb shell am start -n com.apptest1.qatools.manyappstest1/com.apptest1.qatools.manyappstest1.MainActivity
adb shell am start -n com.apptest2.qatools.manyapps02/com.apptest2.qatools.manyapps02.MainActivity
adb shell am start -n com.apptest3.qatools.manyapps03/com.apptest3.qatools.manyapps03.MainActivity
adb shell am start -n com.apptest4.qatools.manyapps04/com.apptest4.qatools.manyapps04.MainActivity
adb shell am start -n com.apptest5.qatools.manyapps05/com.apptest5.qatools.manyapps05.MainActivity
adb shell am start -n com.apptest6.qatools.manyapps06/com.apptest6.qatools.manyapps06.MainActivity
adb shell am start -n com.apptest7.qatools.manyapps07/com.apptest7.qatools.manyapps07.MainActivity
adb shell am start -n com.apptest8.qatools.manyapps08/com.apptest8.qatools.manyapps08.MainActivity
adb shell am start -n com.apptest9.qatools.manyapps/com.apptest9.qatools.manyapps.MainActivity
adb shell am start -n com.apptest10.qatools.manyapps10/com.apptest10.qatools.manyapps10.MainActivity
adb shell am start -n com.apptest11.qatools.manyapps11/com.apptest11.qatools.manyapps11.MainActivity
adb shell am start -n com.apptest12.qatools.manyapps12/com.apptest12.qatools.manyapps12.MainActivity
adb shell am start -n com.apptest13.qatools.manyapps13/com.apptest13.qatools.manyapps13.MainActivity
adb shell am start -n com.apptest14.qatools.manyapps14/com.apptest14.qatools.manyapps14.MainActivity
adb shell am start -n com.apptest15.qatools.manyapps15/com.apptest15.qatools.manyapps15.MainActivity
adb shell am start -n com.apptest16.qatools.manyapps16/com.apptest16.qatools.manyapps16.MainActivity
adb shell am start -n com.apptest17.qatools.manyapps17/com.apptest17.qatools.manyapps17.MainActivity
adb shell am start -n com.apptest18.qatools.manyapps18/com.apptest18.qatools.manyapps18.MainActivity
adb shell am start -n com.apptest19.qatools.manyapps19/com.apptest19.qatools.manyapps19.MainActivity
adb shell am start -n com.apptest20.qatools.manyapps20/com.apptest20.qatools.manyapps20.MainActivity