adb install ManyApp01.apk
adb install ManyApp02.apk
adb install ManyApp03.apk
adb install ManyApp04.apk
adb install ManyApp05.apk
adb install ManyApp06.apk
adb install ManyApp07.apk
adb install ManyApp08.apk
adb install ManyApp09.apk
adb install ManyApp10.apk
adb install ManyApp11.apk
adb install ManyApp12.apk
adb install ManyApp13.apk
adb install ManyApp14.apk
adb install ManyApp15.apk
adb install ManyApp16.apk
adb install ManyApp17.apk
adb install ManyApp18.apk
adb install ManyApp19.apk
adb install ManyApp20.apk